### ISSUE TITLE
真的辣鸡，这个也要搞形式主义，哪怕一天一百个提交又有啥用

### ISSUE THREAD

**Issue by YouWillBe** [justjavac/node-auto-green#1]

**Comment by kk456852** [comment]
u1s1 确实

**Comment by vanton** [comment]
嗯，很神奇为啥会有这种需要

**Comment by justjavac** [comment]
just for fun

**Comment by YouWillBe** [comment]
fun个毛线，有人开源就有人用，有些项目刷星也就算了，连提交记录也要刷，真是特色，弄虚作假最拿手。也别在这说什么工具没有错，错的是使用工具的人，呵呵，有些工具天生就是做坏事的，注意到你专门写出来你21年1.6k的提交，你脸真厚啊
