### ISSUE TITLE
云函数版本报错

### ISSUE THREAD

**Issue by BonjourYY** [justjavac/node-auto-green#2]
### 函数配置如下
![image](https://user-images.githubusercontent.com/42639257/120579417-10081d00-c45a-11eb-8e8f-eefdda7defbf.png)

### 报错信息
![image](https://user-images.githubusercontent.com/42639257/120579726-9886bd80-c45a-11eb-90ce-38c8abb50969.png)

提示信息貌似是没有发现模块，是我函数执行入口写错了还是node依赖没有安装成功呢。麻烦作者帮忙看一下，谢谢。

**Comment by justjavac** [comment]
你云函数的用法不对，你应该先看看云函数的文档。

我这个只是一个 npm 包，没有适配腾讯云函数的入口，腾讯云的入口好像是自己配置的要给函数，好像是需要在 index.js 文件里面写一个 main_hander 的函数。具体的你看看云函数文档吧。
